name: Hardware Tests

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

jobs:
  check_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'Run-CI' }}
    steps:
      - name: Check if label is applied
        run: echo "Label 'Run-CI' applied. Running workflow steps."

  #Include all platforms
  hw_rpi3:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_rpi3.yml@integration

  hw_rpi4:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_rpi4.yml@integration

  hw_odroidc2:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_odroidc2.yml@integration

  hw_sabre:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_sabre.yml@integration

  hw_nitrogen6sx:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_nitrogen6sx.yml@integration