name: Hardware Tests

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

jobs:
  check_label:
    runs-on: self-hosted
    steps:
      - name: Check if label is applied
        run: |
          if [[ $(jq -r '.action' "$GITHUB_EVENT_PATH") == "labeled" && $(jq -r '.label.name' "$GITHUB_EVENT_PATH") == "Run-CI" ]]; then
            echo "Label 'Run-CI' applied. Running workflow steps."
          else
            echo "Label 'Run-CI' not applied. Exiting workflow without running steps."
            exit 78  # Exit with a neutral status to mark the check as pending
          fi

  #Include all platforms
  hw_rpi3:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_rpi3.yml@main

  hw_rpi4:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_rpi4.yml@main

  hw_odroidc2:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_odroidc2.yml@main

  hw_sabre:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_sabre.yml@main

  hw_nitrogen6sx:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/hw_nitrogen6sx.yml@main