name: Qemu Tests

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'Run-CI' }}
    steps:
      - name: Check if label is applied
        run: echo "Label 'Run-CI' applied. Running workflow steps."

  #Include all platforms
  zynq7000_qemu:
    needs: check_label 
    uses: TRENT-OS/trentos/.github/workflows/qemu_zynq7000.yml@integration
    secrets:
      ORG_CLONE_PRV_SUBM: ${{ secrets.ORG_CLONE_PRV_SUBM }}

  sabre_qemu:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/qemu_sabre.yml@integration
    secrets:
      ORG_CLONE_PRV_SUBM: ${{ secrets.ORG_CLONE_PRV_SUBM }}
  
  zynqmp_qemu:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/qemu_zynqmp.yml@integration
    secrets:
      ORG_CLONE_PRV_SUBM: ${{ secrets.ORG_CLONE_PRV_SUBM }}

  qemu-arm-virt_qemu:
    needs: check_label
    uses: TRENT-OS/trentos/.github/workflows/qemu_qemu-arm-virt.yml@integration
    secrets:
      ORG_CLONE_PRV_SUBM: ${{ secrets.ORG_CLONE_PRV_SUBM }}