name: demo_vm_serialserver_hw

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      BUILD_PLAT:
        required: true
        type: string
      TEST_PLAT:
        required: true
        type: string

jobs:
  demo_vm_serialserver_hw:
    runs-on: self-hosted
    env:
      TEST_NAME: "demo_vm_serialserver"
    steps:
      - name: Build ${{ env.TEST_NAME }}
        run: |
          
          trentos/sdk/scripts/open_trentos_build_env.sh -d "-e BUILD_PLATFORM=${{ inputs.BUILD_PLAT }}" trentos/build.sh ${{ env.TEST_NAME }}

      - name: Test ${{ env.TEST_NAME }}
        run: |
          trentos/sdk/scripts/open_trentos_test_env.sh -d "-e BUILD_PLATFORM=${{ inputs.TEST_PLAT }}" trentos/build.sh test-run test_${{ env.TEST_NAME }}.py --system_image=build-${{ inputs.BUILD_PLAT }}-Debug-${{ env.TEST_NAME }}/images/os_image.elf
