name: Hardware RPI3 DEBUG

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-rpi3-hw

env:
  BUILD_PLAT: "rpi3"
  TEST_PLAT: "rpi3-ci"
  PLAT_IP: "10.178.169.40"
  GATEWAY_IP: "10.178.169.33"
  RUNNER_IP: "10.70.192.3" 

jobs:
  #single step as hw tests are not parallelizable & env setup takes a while
  demos_and_tests:
    runs-on: self-hosted
    steps:
      # preparation
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_CLONE_PRV_SUBM }}
          submodules: 'recursive'
          path: 'trentos'
      - name: Test prepare
        run: trentos/sdk/scripts/open_trentos_build_env.sh -d "-e BUILD_PLATFORM=${{ env.BUILD_PLAT }}" trentos/build.sh test-prepare
        working-directory: ${{ github.workspace }}
      - name: Retrieve_Ip
        id: retrieve_ip
        run: echo "ip_address=$(hostname -I | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Claim Hardware
        run: /usr/local/libexec/setup_second_stage/claim_hardware.sh ${{ env.BUILD_PLAT }}

      # tested: reliable
      - name: demo_hello_world
        if: always()
        uses: TRENT-OS/trentos/.github/actions/demo_hello_world@actions-hw-ci
        with:
          BUILD_PLAT: ${{ env.BUILD_PLAT }}
          TEST_PLAT: ${{ env.TEST_PLAT }}